# Variables
@url = http://0.0.0.0:8080
@api = {{url}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTA0ZTA0ZWI2OTFhMjAwZDBkY2Q1OGMiLCJuYW1lIjoiU2tpZGQgUEgiLCJ1c2VyIjoic2tpZGRwaCIsImhjIjoiNDhlMDlmNzY3M2FmY2Y0ZTExOTNkM2VjNjdmY2JiZWUiLCJpYXQiOjE2Mjg2NjM2NTJ9.utRqP5s1qO7ZdjNoqzJRQ3dvy4APUBfZtPfkN1nk-k4

@blog_id = 6113cd1dd2c7da15d006b8d4

@alternate_id = hello-world-3-JhafDLR

### Read Blog Post using blog_id
GET {{api}}/blog/{{blog_id}}

### Read Blog Post using alternate_id
GET {{api}}/blog/{{alternate_id}}

### Reads Blog Posts
GET {{api}}/blogs

### Reads Blog Posts with page
GET {{api}}/blogs/1

### Reads Blog Posts with page and items
GET {{api}}/blogs/2/2

### Write Blog Post
POST {{api}}/blog
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Hello World 3",
    "description": "This is a test post 3",
    "body": "This is a test post 3"
}

### Update Blog Post
PUT {{api}}/blog/{{blog_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{   
    "title": "Blog Post 3 - Hello World >>===+++",
    "description": "This is an updated test post from blog post 3",
    "body": "This is an updated test post from blog post 3"
}

### Delete Blog Post
DELETE {{api}}/blog/{{blog_id}}
Authorization: Bearer {{token}}

### Delete All Blog Post
DELETE {{api}}/blogs
Authorization: Bearer {{token}}