# Variables
@url = http://0.0.0.0:8080/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTE3ZTZlNmZjMjMxYTA4ODg2NjU4YTIiLCJuYW1lIjoiSmVyaWNobyBBcXVpbm8iLCJ1c2VyIjoiZXJ1MTIzIiwiaWF0IjoxNjMwNjU2MDkwfQ.A2EfUmYNSJN8e8-jcMnyG0l_qF97sVjg_uiGqtl2mW0

# _id or alternative_id
@id = 6131da39c4d8df1434775d07

### Create
POST {{url}}/classroom
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Classroom 1"
}

### Read
GET {{url}}/classroom/{{id}}

### Update
PUT {{url}}/classroom/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Classroom 2"
}

### Delete
DELETE {{url}}/classroom/{{id}}
Authorization: Bearer {{token}}


# Listing

### Listing public classrooms
GET {{url}}/classrooms/public/1/5

### Listing managed classrooms
GET {{url}}/classrooms/managed/1/5
Authorization: Bearer {{token}}