@url = http://0.0.0.0:8080
@api = {{url}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTE3ZTZlNmZjMjMxYTA4ODg2NjU4YTIiLCJuYW1lIjoiSmVyaWNobyBBcXVpbm8iLCJ1c2VyIjoiZXJ1MTIzIiwiaGMiOiJiNWVkMWJjNDQwODIzYTVjODlkMmFlM2RiNjZkN2ZhYiIsImlhdCI6MTYyODk1NjM5MH0.Jn9qSHb6o2LUSAWFkSNbx7dvlBxgmU9qud0XOjWnzyY
@user = eru123
@codename = myapi
@codebody = __RESPONSE__.send({message:'Yahoo! First API'})
@updatedcodebody = __RESPONSE__.send({message:'Yahoo! Second API'})
### GET CodExecs
GET {{url}}/myapi/{{user}}/{{codename}}

### Create API
POST {{api}}/myapi
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "codename": "{{codename}}",
    "codebody": "{{codebody}}"
}

### Read API using alternate_id
GET {{api}}/myapi/{{codename}}
Authorization: Bearer {{token}}

### Reads APIs
GET {{api}}/myapis
Authorization: Bearer {{token}}

### Reads APIs with page
GET {{api}}/myapis/1
Authorization: Bearer {{token}}

### Reads APIs with page and items
GET {{api}}/myapis/1/2
Authorization: Bearer {{token}}

### Update API
PUT {{api}}/myapi/{{codename}}
Authorization: Bearer {{token}}
Content-Type: application/json

{   
    "codename": "{{codename}}",
    "codebody": "{{updatedcodebody}}"
}

### Delete API
DELETE {{api}}/myapi/{{codename}}
Authorization: Bearer {{token}}

### Delete All APIs
DELETE {{api}}/myapis
Authorization: Bearer {{token}}