# Variables
@url = http://0.0.0.0:8080
@api = {{url}}/api
@name = Jericho Aquino
@email = yeoligoakino@gmail.com
@phone = +639206080487
@user = eru123
@pass = !P4s5W04d~
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTM2MDQ5YjlhMWNhM2M4ODdjZGI4ZGYiLCJuYW1lIjoiSmVyaWNobyBBcXVpbm8iLCJ1c2VyIjoiZXJ1MTIzIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMwOTg3Njg1fQ.80OMs0o2zkWkAyYKPGqFtOFUCEnrFi1u9tVvEA6phM0
@id = 6136049b9a1ca3c887cdb8df

### Create User
POST {{api}}/auth/register
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "phone": "{{phone}}",
  "pass": "{{pass}}",
  "user": "{{user}}"
}

### Login
POST {{api}}/auth/login
Content-Type: application/json

{
  "user": "{{user}}",
  "pass": "{{pass}}"
}

### Read User by token
GET {{api}}/user
Authorization: Bearer {{token}}

### Read User By Username
GET {{api}}/user/{{user}}
Authorization: Bearer {{token}}

### Read user by id
GET {{api}}/user/{{id}}
Authorization: Bearer {{token}}

### GET users
GET {{api}}/users/1/100
Authorization: Bearer {{token}}

### UPDATE user
PUT {{api}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "user": "eru123",
  "pass": "{{pass}}"
}
### DELETE user
DELETE {{api}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "user": "eru123",
  "pass": "{{pass}}"
}

### Read Current Session
GET {{api}}/auth/session
Authorization: Bearer {{token}}

### Read other Session
GET {{api}}/auth/session/613610a74f679a58a145dcbb
Authorization: Bearer {{token}}

### Read all sessions
GET {{api}}/auth/sessions/all
Authorization: Bearer {{token}}

### Read other sessions
GET {{api}}/auth/sessions/1/5
Authorization: Bearer {{token}}

### Logout current session
DELETE {{api}}/auth/logout
Authorization: Bearer {{token}}

### Logout other session
DELETE {{api}}/auth/logout/session/61360e0e5a6733bad19895ba
Authorization: Bearer {{token}}

### Logout all sessions except current session
DELETE {{api}}/auth/logout/all
Authorization: Bearer {{token}}