# Variables
@url = http://0.0.0.0:8080
@api = {{url}}/api
@name = Jericho Aquino
@user = eru123
@pass = Password123

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGRkZmJjOGRlY2YwMjA5YjAwZGNjZGYiLCJuYW1lIjoiSmVyaWNobyBBcXVpbm8iLCJ1c2VyIjoiZXJ1MTIzIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2MjUxOTQyOTR9.KiAknrY6DNghkXJCHSMpaJYr7J2PS-pqaKhhKOA5MYo
@id = 60de977d27f1ac1ca8c3c35f

### Create User
POST {{api}}/users/register
Content-Type: application/json

{
  "name": "{{name}}",
  "user": "{{user}}",
  "pass": "{{pass}}"
}

### Login
POST {{api}}/auth/login
Content-Type: application/json

{
  "user": "{{user}}",
  "pass": "{{pass}}"
}

### Read User By Username
GET {{api}}/user/@{{user}}
Authorization: Bearer {{token}}

### Read user by id
GET {{api}}/user/${{id}}
Authorization: Bearer {{token}}