<template>
  <div>
    <h1>Home sweet home</h1>
    
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium nesciunt iure suscipit cupiditate magni voluptatibus quod ab quisquam impedit adipisci esse laboriosam, error vel cumque est earum officia quae. Eius repellat eum, nesciunt magni, eos quia reiciendis, a praesentium hic ab exercitationem deserunt minima repudiandae consequuntur vero error. Totam at, culpa, dolorem ab distinctio porro animi, voluptate quo id molestias inventore ratione? Accusantium esse cum, aperiam animi maiores excepturi enim. Laboriosam placeat voluptas tempore facilis rem veritatis sequi quae possimus.</p>
  </div>
</template>
<script>
export default {
  async created(){
    const me = await this.$tuos.auth.userMe()
    console.log(me)
  }
}
</script>